#!/bin/bash

# ANSI color variables (BOLD)
NColor='\033[0m'      # No Color
BRed='\033[1;31m'     # Red
BGreen='\033[1;32m'   # Green
BYellow='\033[1;33m'  # Yellow

# check if only one URL is passed and set URL variable
if [ $# -eq 0 ]; then
    echo -e "${BYellow}Please enter a URL.${NColor}"
    read -p "URL: " URL
    if [ -z "$URL" ]; then
        echo -e "${BRed}No URL provided. Exiting.${NColor}"
        exit 1
    fi
elif [ $# -ne 1 ]; then
    echo -e "${BRed}Expected 1 argument, but $# provided. Exiting.${NColor}"
    exit 1
else
    URL=$1
fi

# set download app
APP="yt-dlp"

# set download app options
OPT="-o %(title)s.%(ext)s
     --restrict-filenames
     --windows-filenames
     --embed-thumbnail
     --concurrent-fragments 8
     --no-part"

echo -e ""

# show format options for download
RESPONSE=`unbuffer $APP -F "$URL" 2>&1 | tee /dev/tty`

# show message for URL problems
if grep -q "ERROR:" <<< "$RESPONSE" ; then 
echo -e "\n${BRed}Download Failed! Please check the error message above. Exiting.${NColor}"
exit 1
fi

# get format option
echo -e "\n${BYellow}Choose format by ID.${NColor}"
read -p "ID: " ID
echo -e ""

# dowload
if [ "$ID" = "" ];
then $APP "$URL" $OPT
else RESPONSE=`unbuffer $APP -f "$ID" "$URL" $OPT 2>&1 | tee /dev/tty`
fi

# final message
if grep -q "ERROR:" <<< "$RESPONSE";
then echo -e "\n${BRed}Download Failed! Please check the error message above. Exiting.${NColor}"
else echo -e "\n${BGreen}Download Completed Successfully!${NColor}"
fi