#!/bin/bash

# Check if a URL is passed as an argument
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <url>"
    exit 1
fi

# ANSI Color variables (BOLD)
NColor='\033[0m'      # No Color
BRed='\033[1;31m'     # Red
BGreen='\033[1;32m'   # Green
BYellow='\033[1;33m'  # Yellow

# Video URL
URL=$1

# Download app
APP="yt-dlp"

# App options
OPT="-o %(title)s.%(ext)s
     --restrict-filenames
     --windows-filenames
     --merge-output-format mp4
     --remux-video mp4
     --embed-thumbnail"

echo -e ""

# Show format options for download
$APP -F "$URL"

# Get format option
echo -e "\n${BYellow}Choose format by ID.${NColor}"
read -p "ID: " ID
echo ""

# Dowload
if [ "$ID" = "" ];
then $APP "$URL" $OPT
else RESPONSE=`$APP -f "$ID" "$URL" $OPT 2>&1 | tee /dev/tty`
fi

# Final message
if grep -q "ERROR:" <<< "$RESPONSE";
then echo -e "\n${BRed}Download Failed! Check error message above.${NColor}"
else echo -e "\n${BGreen}Download Completed Successfully!${NColor}"
fi
